//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSSystemEntity.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CodinovaDBContext : DbContext
    {
        public CodinovaDBContext()
            : base("name=CodinovaDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        [DbFunction("CodinovaDBContext", "ufn_GetAllProducts")]
        public virtual IQueryable<ufn_GetAllProducts_Result> ufn_GetAllProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ufn_GetAllProducts_Result>("[CodinovaDBContext].[ufn_GetAllProducts]()");
        }
    
        public virtual int usp_InsertSaleDetails(string emailId, Nullable<decimal> totalSaleAmount, ObjectParameter saleId)
        {
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var totalSaleAmountParameter = totalSaleAmount.HasValue ?
                new ObjectParameter("TotalSaleAmount", totalSaleAmount) :
                new ObjectParameter("TotalSaleAmount", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertSaleDetails", emailIdParameter, totalSaleAmountParameter, saleId);
        }
    }
}
